import type { NextPage } from "next";
import Head from "next/head";
import GoalImageIcon from "../components/GoalImageIcon";
import { useCallback, useEffect, useState } from "react";
import useGoals from "../hooks/useGoals";
import usePlayers from "../hooks/usePlayers";
import {
  countAvailableMemberCount,
  defaultUsers,
  matches,
  Player,
  title,
  User,
} from "../lib/mahjong";
import { getToday } from "../lib/util";

const Home: NextPage = () => {
  const { data: goals } = useGoals();
  const { data, isError, isLoading } = usePlayers();
  const [users, setUsers] = useState(defaultUsers);
  const [filteredMatches, setFilteredMatches] = useState(matches);

  useEffect(() => {
    if (!data) return;
    let newValue: User[] = [];

    defaultUsers.forEach((user) => {
      let player = data.find((item: Player) => item.name === user.name);
      if (player) {
        user.checked = player.canPlay;
        user.pageId = player.page.id;
      }
      newValue.push(user);
    });

    setUsers(newValue);
  }, [data]);

  const clickClearEventHandler = useCallback(() => {
    setUsers((s) => {
      return s.map((ss) => {
        return {
          ...ss,
          checked: false,
        };
      });
    });
    try {
      users.forEach(async (user) => {
        const r = await fetch(`/api/${user.pageId}/clear`);
        const d = await r.json();
      });
    } catch (error) {
      console.error(error);
    }
  }, [users]);

  const clickEventHandler = useCallback(async (e: User) => {
    e.checked = !e.checked;
    setUsers((old) => [
      ...old.filter((user) => user.id < e.id),
      e,
      ...old.filter((user) => user.id > e.id),
    ]);
    try {
      const r = await fetch(
        `/api/${e.pageId}/edit?canPlay=${
          e.checked ? "1" : "0"
        }&date=${getToday()}`
      );
      const d = await r.json();
    } catch (error) {
      console.error(error);
    }
  }, []);

  if (isLoading) return null;
  if (isError) return null;

  const goal = goals[Math.floor(Math.random() * goals.length)];

  return (
    <div className="bg-gradient-to-br from-green-800/90 via-green-800/90 to-green-800/90 select-none min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative">
        <div className="flex justify-between bg-gradient-to-r from-rose-500 via-rose-400 to-rose-300 text-white p-1">
          <h1 className="font-bold text-2xl ">{title}</h1>
        </div>
        <GoalImageIcon {...goal} />

        <div className="p-2">
          <div className="mb-4">
            <span className="font-bold text-white text-base">メンバー</span>
          </div>
          <div className="flex flex-col space-y-4 xl:space-y-0 xl:flex-row">
            <div className="flex space-x-1 sm:space-x-2 md:space-x-3 xl:space-x-4 items-center font-serif">
              {users.map((user) => {
                return user.name.length > 2 ? (
                  user.checked ? (
                    <div
                      key={user.id}
                      className="common color-one size-one janpai"
                      onClick={() => clickEventHandler(user)}
                    >
                      {user.name}
                    </div>
                  ) : (
                    <div
                      key={user.id}
                      className="common color-two size-one janpai"
                      onClick={() => clickEventHandler(user)}
                    >
                      {user.name}
                    </div>
                  )
                ) : user.checked ? (
                  <div
                    key={user.id}
                    className="common color-one size-two"
                    onClick={() => clickEventHandler(user)}
                  >
                    <div className="absolute inset-0 rounded-md bg-white"></div>
                    <div className="z-10 drop-shadow-xl">{user.name}</div>
                  </div>
                ) : (
                  <div
                    key={user.id}
                    className="common color-two size-two"
                    onClick={() => clickEventHandler(user)}
                  >
                    <div className="absolute inset-0 rounded-md bg-blue-500"></div>
                    <div className="z-10 drop-shadow-xl">{user.name}</div>
                  </div>
                );
              })}
              {users.some((user) => user.checked) ? (
                <div
                  className="bg-yellow-500 text-yellow-50 text-center whitespace-nowrap px-4 rounded border border-yellow-500 select-none cursor-pointer shadow shadow-yellow-500 uppercase"
                  onClick={() => clickClearEventHandler()}
                >
                  流局
                </div>
              ) : (
                <></>
              )}
            </div>
          </div>
          <hr className="my-3" />
          <div className="font-bold text-white text-base">マッチング状況</div>
          <div className="w-[800px] xl:w-[1280px] grid sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 grid-flow-row-dense gap-1 md:gap-2 2xl:gap-4">
            {filteredMatches.map(({ id, name, users: matchUsers, done }) => {
              const numOfAvailable = countAvailableMemberCount(
                users,
                matchUsers
              );
              return (
                <div
                  key={id}
                  className={`w-[180px] xl:w-[300px] h-[180px] xl:h-[300px] rounded-lg border-2 2xl:border-8 border-green-900 bg-[green] ${
                    done ? "order-1" : ""
                  }`}
                >
                  <div className="flex justify-between items-center m-1 xl:m-4 font-serif">
                    <span className="text-3xl xl:text-5xl">{name}</span>
                    {done === true ? (
                      <span className="text-lg xl:text-2xl px-2 xl:px-4 py-px xl:py-1 rounded-md bg-rose-500 text-white xl:shadow-sm shadow-rose-500/80">
                        対局済
                      </span>
                    ) : numOfAvailable === 4 ? (
                      <span className="text-lg xl:text-2xl px-2 xl:px-4 py-px xl:py-1 rounded-md bg-[blue] text-white xl:shadow-sm shadow-[blue]/80">
                        聴牌
                      </span>
                    ) : numOfAvailable === 3 ? (
                      <span className="text-lg xl:text-2xl px-2 xl:px-4 py-px xl:py-1 rounded-md bg-[orange] text-white xl:shadow-sm shadow-[orange]/80">
                        一向聴
                      </span>
                    ) : numOfAvailable === 2 ? (
                      <span className="text-lg xl:text-2xl px-2 xl:px-4 py-px xl:py-1 rounded-md bg-rose-500 text-white xl:shadow-sm shadow-rose-500/80">
                        二向聴
                      </span>
                    ) : numOfAvailable === 1 ? (
                      <span className="text-lg xl:text-2xl px-2 xl:px-4 py-px xl:py-1 rounded-md bg-[brown] text-white xl:shadow-sm shadow-[brown]/80">
                        三向聴
                      </span>
                    ) : (
                      <span className="text-lg xl:text-2xl px-2 xl:px-4 py-px xl:py-1 rounded-md bg-[purple] text-white xl:shadow-sm shadow-[purple]/80">
                        四向聴
                      </span>
                    )}
                  </div>
                  <div className="mt-4 xl:mt-10 flex justify-between text-center m-2 xl:m-4 items-center font-serif xl:gap-4 tracking-wide">
                    {matchUsers.map(({ name, score }, index) => {
                      let y = users.filter(
                        (user) => user.checked && user.name === name
                      );
                      return y && y.length > 0 && !done ? (
                        <div
                          key={index}
                          className="text-2xl xl:text-4xl w-16 h-20 text-[orange]"
                        >
                          {name}
                          {done ? (
                            <>
                              <br />
                              <span className={`font-mono font-bold text-xl ${score > 0 ? "text-[blue]" : "text-red-50"}`}>
                                {score > 0 ? "+" : ""}
                                {score}
                              </span>
                            </>
                          ) : null}
                        </div>
                      ) : (
                        <div
                          key={index}
                          className="text-2xl xl:text-4xl w-16 h-20 text-slate-400"
                        >
                          {name}
                          {done ? (
                            <>
                              <br />
                              <span className={`font-mono font-bold text-xl ${score > 0 ? "text-[blue]" : "text-red-50"}`}>
                                {score > 0 ? "+" : ""}
                                {score}
                              </span>
                            </>
                          ) : null}
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
