import type { NextPage } from "next";
import Head from "next/head";
import GoalImageIcon from "../components/GoalImageIcon";
import useGoals from "../hooks/useGoals";

const Home: NextPage = () => {
  const { data: goals, isLoading, isError } = useGoals();

  if (isLoading) return null;
  if (isError) return null;

  const goal = goals[Math.floor(Math.random() * goals.length)];

  return (
    <div className="bg-gradient-to-br from-green-800/90 via-green-800/90 to-green-800/90 select-none min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative">
        <GoalImageIcon {...goal} />
      </main>
    </div>
  );
};

export default Home;
